application: swansonbassign4
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*/css
  static_dir: css

- url: .*/fonts
  static_dir: fonts

- url: .*/js
  static_dir: js

- url: /img
  static_dir: img

- url: /testData/.*
  script: testData.app
  login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
